# Generated by Django 4.2.2 on 2023-07-31 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('isPartyLeader', models.BooleanField(default=False)),
                ('points', models.IntegerField(default=0)),
                ('channel_name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('word', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('occupancy', models.IntegerField(default=4)),
                ('maxRounds', models.IntegerField()),
                ('currentRound', models.IntegerField(default=1)),
                ('isJoin', models.BooleanField(default=True)),
                ('turnIndex', models.IntegerField(default=0)),
                ('players', models.ManyToManyField(related_name='rooms', to='scribbleapp.player')),
                ('turn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turns', to='scribbleapp.player')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
